vowel: count_vowels_exe
	./count_vowels_exe

consonant: count_consonants_exe
	./count_consonants_exe

count_vowels_exe: count_vowels.o master.o
	gcc -o count_vowels_exe count_vowels.o master.o

count_consonants_exe: count_consonants.o master.o
	gcc -o count_consonants_exe count_consonants.o master.o

count_vowels.o: count_vowels.c
	gcc -c count_vowels.c

count_consonants.o: count_consonants.c
	gcc -c count_consonants.c

master.o: master.c
	gcc -c master.c

clean_vowel:
	rm -rf *.o
	rm count_vowels_exe

clean_consonant:
	rm -rf *.o
	rm count_consonants_exe
